environment: {}
parameters: {}
packages:
  - name: ftx
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: funding
        binary: false
        main: ""
        runtime: "go:default"
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
